localibrary/catalog/urls.py
from django.urls import path 
from . import views

urlpatterns=[
    path('', views.index, name='index'),
    path('search/', views.SearchView, name='search_results'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='detail'),
    path('reviews/new//<int:pk>/', views.ReviewCreateView.as_view(), name='review-create'),
    path('reserve/<pk>', views.ReserveBook, name='reserve'),
]

localibrary/localibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
from django.contrib.auth import views as auth_views
from accounts import views as user_views

urlpatterns +=[
    path('accounts/',include('accounts.urls')),
    path('catalog/',include('catalog.urls'),name='home'),
    
    
]
from django.views.generic import RedirectView

urlpatterns +=[
	path('',RedirectView.as_view(url='catalog/',permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static 

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

localibrary/catalog/models.py
from django.db import models
from accounts.models import Profile
from django.contrib.auth.models import User
import uuid
from django.contrib import messages
from django.urls import reverse
from field_history.tracker import FieldHistoryTracker 
# Create your models here.

class Genre(models.Model):
    name=models.CharField(max_length=200,help_text="Enter a Genra(e.g Detective)")
    #History = FieldHistoryTracker(['name'])
    def __str__(self):
        return self.name

class Book(models.Model):
    
    title=models.CharField(max_length=200)
    author=models.ForeignKey('Author',on_delete=models.SET_NULL,null=True)
    summary=models.TextField(max_length=1000,help_text="Enter a brief desciption of Book")
    isbn=models.CharField("ISBN",max_length=13,help_text="13 Character ISBN Number")
    genre=models.ManyToManyField(Genre,help_text="Select a genre for this book!")
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})
class Reviews(models.Model):
    book=models.ForeignKey("Book",on_delete=models.PROTECT,db_constraint=False,null=True)
    Reviewuser=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    review=models.CharField(max_length=200)
    

class BookInstance(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,help_text="Unique ID")
    book=models.ForeignKey("Book",on_delete=models.PROTECT,db_constraint=True,null=True)
    imprint=models.CharField(max_length=200)
    due_back=models.DateField(null=True,blank=True)
    LOAN_STATUS =(
        ('a','Available'),
        ('r','Reserved'),
    )
    BookUser=models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)
    Languages=(
        ('ab', 'Abkhaz'),
        ('aa', 'Afar'),
        ('af', 'Afrikaans'),
        ('ak', 'Akan'),
        ('sq', 'Albanian'),
        ('am', 'Amharic'),
        ('ar', 'Arabic'),
        ('an', 'Aragonese'),
        ('hy', 'Armenian'),
        ('as', 'Assamese'),
        ('av', 'Avaric'),
        ('ae', 'Avestan'),
        ('ay', 'Aymara'),
        ('az', 'Azerbaijani'),
        ('bm', 'Bambara'),
        ('ba', 'Bashkir'),
        ('eu', 'Basque'),
        ('be', 'Belarusian'),
        ('bn', 'Bengali'),
        ('bh', 'Bihari'),
        ('bi', 'Bislama'),
        ('bs', 'Bosnian'),
        ('br', 'Breton'),
        ('bg', 'Bulgarian'),
        ('my', 'Burmese'),
        ('ca', 'Catalan; Valencian'),
        ('ch', 'Chamorro'),
        ('ce', 'Chechen'),
        ('ny', 'Chichewa; Chewa; Nyanja'),
        ('zh', 'Chinese'),
        ('cv', 'Chuvash'),
        ('kw', 'Cornish'),
        ('co', 'Corsican'),
        ('cr', 'Cree'),
        ('hr', 'Croatian'),
        ('cs', 'Czech'),
        ('da', 'Danish'),
        ('dv', 'Divehi; Maldivian;'),
        ('nl', 'Dutch'),
        ('dz', 'Dzongkha'),
        ('en', 'English'),
        ('eo', 'Esperanto'),
        ('et', 'Estonian'),
        ('ee', 'Ewe'),
        ('fo', 'Faroese'),
        ('fj', 'Fijian'),
        ('fi', 'Finnish'),
        ('fr', 'French'),
        ('ff', 'Fula'),
        ('gl', 'Galician'),
        ('ka', 'Georgian'),
        ('de', 'German'),
        ('el', 'Greek, Modern'),
        ('gn', 'Guaraní'),
        ('gu', 'Gujarati'),
        ('ht', 'Haitian'),
        ('ha', 'Hausa'),
        ('he', 'Hebrew (modern)'),
        ('hz', 'Herero'),
        ('hi', 'Hindi'),
        ('ho', 'Hiri Motu'),
        ('hu', 'Hungarian'),
        ('ia', 'Interlingua'),
        ('id', 'Indonesian'),
        ('ie', 'Interlingue'),
        ('ga', 'Irish'),
        ('ig', 'Igbo'),
        ('ik', 'Inupiaq'),
        ('io', 'Ido'),
        ('is', 'Icelandic'),
        ('it', 'Italian'),
        ('iu', 'Inuktitut'),
        ('ja', 'Japanese'),
        ('jv', 'Javanese'),
        ('kl', 'Kalaallisut'),
        ('kn', 'Kannada'),
        ('kr', 'Kanuri'),
        ('ks', 'Kashmiri'),
        ('kk', 'Kazakh'),
        ('km', 'Khmer'),
        ('ki', 'Kikuyu, Gikuyu'),
        ('rw', 'Kinyarwanda'),
        ('ky', 'Kirghiz, Kyrgyz'),
        ('kv', 'Komi'),
        ('kg', 'Kongo'),
        ('ko', 'Korean'),
        ('ku', 'Kurdish'),
        ('kj', 'Kwanyama, Kuanyama'),
        ('la', 'Latin'),
        ('lb', 'Luxembourgish'),
        ('lg', 'Luganda'),
        ('li', 'Limburgish'),
        ('ln', 'Lingala'),
        ('lo', 'Lao'),
        ('lt', 'Lithuanian'),
        ('lu', 'Luba-Katanga'),
        ('lv', 'Latvian'),
        ('gv', 'Manx'),
        ('mk', 'Macedonian'),
        ('mg', 'Malagasy'),
        ('ms', 'Malay'),
        ('ml', 'Malayalam'),
        ('mt', 'Maltese'),
        ('mi', 'Māori'),
        ('mr', 'Marathi (Marāṭhī)'),
        ('mh', 'Marshallese'),
        ('mn', 'Mongolian'),
        ('na', 'Nauru'),
        ('nv', 'Navajo, Navaho'),
        ('nb', 'Norwegian Bokmål'),
        ('nd', 'North Ndebele'),
        ('ne', 'Nepali'),
        ('ng', 'Ndonga'),
        ('nn', 'Norwegian Nynorsk'),
        ('no', 'Norwegian'),
        ('ii', 'Nuosu'),
        ('nr', 'South Ndebele'),
        ('oc', 'Occitan'),
        ('oj', 'Ojibwe, Ojibwa'),
        ('cu', 'Old Church Slavonic'),
        ('om', 'Oromo'),
        ('or', 'Oriya'),
        ('os', 'Ossetian, Ossetic'),
        ('pa', 'Panjabi, Punjabi'),
        ('pi', 'Pāli'),
        ('fa', 'Persian'),
        ('pl', 'Polish'),
        ('ps', 'Pashto, Pushto'),
        ('pt', 'Portuguese'),
        ('qu', 'Quechua'),
        ('rm', 'Romansh'),
        ('rn', 'Kirundi'),
        ('ro', 'Romanian, Moldavan'),
        ('ru', 'Russian'),
        ('sa', 'Sanskrit (Saṁskṛta)'),
        ('sc', 'Sardinian'),
        ('sd', 'Sindhi'),
        ('se', 'Northern Sami'),
        ('sm', 'Samoan'),
        ('sg', 'Sango'),
        ('sr', 'Serbian'),
        ('gd', 'Scottish Gaelic'),
        ('sn', 'Shona'),
        ('si', 'Sinhala, Sinhalese'),
        ('sk', 'Slovak'),
        ('sl', 'Slovene'),
        ('so', 'Somali'),
        ('st', 'Southern Sotho'),
        ('es', 'Spanish; Castilian'),
        ('su', 'Sundanese'),
        ('sw', 'Swahili'),
        ('ss', 'Swati'),
        ('sv', 'Swedish'),
        ('ta', 'Tamil'),
        ('te', 'Telugu'),
        ('tg', 'Tajik'),
        ('th', 'Thai'),
        ('ti', 'Tigrinya'),
        ('bo', 'Tibetan'),
        ('tk', 'Turkmen'),
        ('tl', 'Tagalog'),
        ('tn', 'Tswana'),
        ('to', 'Tonga'),
        ('tr', 'Turkish'),
        ('ts', 'Tsonga'),
        ('tt', 'Tatar'),
        ('tw', 'Twi'),
        ('ty', 'Tahitian'),
        ('ug', 'Uighur, Uyghur'),
        ('uk', 'Ukrainian'),
        ('ur', 'Urdu'),
        ('uz', 'Uzbek'),
        ('ve', 'Venda'),
        ('vi', 'Vietnamese'),
        ('vo', 'Volapük'),
        ('wa', 'Walloon'),
        ('cy', 'Welsh'),
        ('wo', 'Wolof'),
        ('fy', 'Western Frisian'),
        ('xh', 'Xhosa'),
        ('yi', 'Yiddish'),
        ('yo', 'Yoruba'),
        ('za', 'Zhuang, Chuang'),
        ('zu', 'Zulu'),
    )
    status=models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',

    )
    Lang=models.CharField(
        max_length=2,
        choices=Languages,
        blank=True,
        default='m',
        help_text='Languages',

    )
    
    class Meta:
        ordering=['due_back']

    def __str__(self):
         return f'{self.id}({self.book.title})'

class Author(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    data_of_birth=models.DateField(null=True,blank=True)
    date_of_death=models.DateField('Died',null=True,blank=True)
    class Meta:
        ordering=['last_name','first_name']
    def __str__(self):
        return f'{self.last_name}{self.first_name}'
class UserHistory(models.Model):
    bookInstance=models.ForeignKey("BookInstance",on_delete=models.PROTECT,db_constraint=True,null=True)
    BookUser=models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)

localibrary/catalog/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
<<<<<<< Updated upstream
=======
from django.contrib.auth.decorators import user_passes_test
>>>>>>> Stashed changes
from django.views.generic.base import ContextMixin
from django.contrib.auth.decorators import login_required,user_passes_test
from django.http import HttpResponse
from .models import Book,BookInstance,Reviews
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.models import User

def not_in_admin(user):
<<<<<<< Updated upstream
    return not user.groups.filter(name='Admin').exists() and not user.groups.filter(name='Book Manager').exists()
def in_student(user):
    return  user.groups.filter(name='Student/Teacher').exists() 
=======
    return  not user.groups.filter(name='Admin').exists() and  not user.groups.filter(name='Book Manager').exists()
def in_student(user):
    return   user.groups.filter(name='Student/Teacher').exists() 
>>>>>>> Stashed changes
@user_passes_test(not_in_admin, login_url='login')
def index(request):
    book_list=Book.objects.order_by('-title')
    
    context={'book_list':book_list}
    
    return render(request,'catalog/index.html',context)
<<<<<<< Updated upstream
=======

>>>>>>> Stashed changes
@user_passes_test(not_in_admin, login_url='login')
def SearchView(request):
    model=Book
    if request.method=="POST":
        temlplate_name="catalog/search_results.html"
        query=request.POST.get('q')
        object_list=model.objects.filter(Q(title__icontains=query))
        context={'book_list':object_list}
        return render(request,temlplate_name,context)
class BookDetailView(DetailView):
    model = Book

<<<<<<< Updated upstream
=======

>>>>>>> Stashed changes
class ReviewCreateView(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Reviews
    fields=['review']
    success_url="/catalog/"
    def get_context_data(self, **kwargs):
        ctx = super(ReviewCreateView, self).get_context_data(**kwargs)
        ctx['Book'] = Book.objects.get(id=self.kwargs['pk'])

        return ctx
    def form_valid(self, form):
        ctx=self.get_context_data()
        form.instance.book=ctx['Book']
        form.instance.Reviewuser = self.request.user
        return super().form_valid(form)
    def test_func(self):
<<<<<<< Updated upstream
        return self.request.user.groups.fitler(name='Student/Teacher').exists() 
=======
        return self.request.user.groups.filter(name='Student/Teacher').exists()
>>>>>>> Stashed changes
@user_passes_test(in_student, login_url='login')
def ReserveBook(request,pk):
    Instance=BookInstance.objects.get(id=pk)
   
    if request.user.is_authenticated==True:
        if Instance.status=='a':
            Instance.status='r'
            Instance.BookUser=request.user
            Instance.save()
        else:
            messages.error(request, 'BOOK ALREADY RESERRVED')
        return redirect('/catalog/')
    else:
        messages.error(request, 'NEED TO BE LOGIN TO RESERVE BOOK')
        return redirect('login')
"""class ReserveBook(ContextMixin,View):
    model=BookInstance
    def get_context_data(self, **kwargs):
        ctx = super(ReserveBook,self).get_context_data(**kwargs)
        ctx['BookInstance']=BookInstance.objects.get(pk)
        return ctx
    def get(self, request, *args, **kwargs):
        ctx=self.get_context_data()
        ctx['BookInstance'].status="a"
        return redirect('/catalog/')"""

localibrary/catalog/templates/catalog/base.html
{%load static%}
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>

<header class="site-header">

      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
        
          <a class="navbar-brand mr-4" href="{% url 'index' %}">Library</a>
           
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
            </div>
            
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>

                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {%endif%}
              
            </div>
          </div>
        </div>
      </nav>
    </header>
     <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
           {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-danger">
                    {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
          {% endif %}
        </div>
        </main>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

localibrary/catalog/templates/catalog/book_detail.html
 {% extends "catalog/base.html" %}
 {% block content %}
 <h1> {{ book.title }}</h1>

  <p><strong>Author:</strong> {{ book.author }}</p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 

  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>  
  <h4>Reviews</h4>
    {% for review in book.reviews_set.all %}
      <hr>
      <p><strong>Reviews:</strong> {{ review.review }}</p>
      <p class="text-muted"><strong>By</strong> {{ review.Reviewuser }}</p>
    {% endfor %}
     <button class="btn btn-outline-info" type="button" onclick="location.href='{% url 'review-create' pk=book.id %}'" >Review Book</button>
  </div>
  
  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p><strong>Languange:</strong> {{ copy.Lang }}</p>
      <button class="btn btn-outline-info" type="button" onclick="location.href='{% url 'reserve' pk=copy.id %}'" >Borrow Book</button>
    {% endfor %}
     
{% endblock content %}

localibrary/catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}
{%load static%}
{% block content %}

<div class="topnav">
<form action="{% url 'search_results'%}" method="post"> 
  <input  name="q" type="text" placeholder="Search..">
  <button type="submit" formaction="{% url 'search_results'%}">Submit</button>
  {% csrf_token %}
</form>
</div>
{%for book in book_list%}
<article class="media content-section">
          <div class="media-body">
            <div class="book-metadata">
              <div class="mr-2">{{ book.author }}</div>
            </div>
            <h2><a class="book-title" href="{% url 'detail'  book.id %}">{{ book.title }}</a></h2>
          </div>
        </article>

{%endfor%}

{% endblock content %}

localibrary/catalog/templates/catalog/reviews_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% block content%}
<div class="content-section">
    <form method="post">
    {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Review</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Post</button>
        </div>
    </form>
    
</div>
{% endblock %}

localibrary/catalog/templates/catalog/search_results.html
{% extends "catalog/base.html" %}
{% block content %}
{%for book in book_list%}
<article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <p>{{ book.author }}</p>
            </div>
            <h2><a class="article-title" href="{% url 'detail'  book.id %}">{{ book.title }}</a></h2>
          </div>
        </article>
{% endfor %}
{% endblock content %}